### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict'

### ISSUE THREAD

**Issue by JordanShackelford** [vingtfranc/LoLAnalyzer#1]
generating for: Carry
bans ['alistar', 'amumu', 'ashe', 'evelynn', 'ashe', 'ziggs', 'warwick', 'sion', 'ziggs', 'sejuani']
picks [('akali', 'Jungle', 1), ('...', 'Carry', 1), ('...', '...', 1), ('...', '...', 1), ('...', '...', 1), ('alistar', 'Jungle', 0), ('annie', 'Support', 0), ('...', '...', 0), ('...', '...', 0), ('...', '...', 0)]
<class 'AttributeError'> 'NoneType' object has no attribute 'predict' <traceback object at 0x0000023AA23E1D48>
Traceback (most recent call last):
  File "BestPicks.py", line 197, in <lambda>
    self.generateButton.clicked.connect(lambda: self.generate())
  File "BestPicks.py", line 517, in generate
    pred_values = self.network.model.predict(np.array(data), batch_size=len(data))
AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by VRichardJP** [comment]
This is curious, self.network.model is set once at line 374:
`
        self.network.model = keras.models.load_model(model_file)
`
Something is wrong with the model_file you use (did you train your own network?)

**Comment by JordanShackelford** [comment]
I'm just trying to use the demo model before I train my own network. I copied ABR_TJMCS_DenseUniform_5_1024.h5 from the examples folder and put it in DB/models. When I run python BestPicks.py it immediately gives an error saying "Cannot find "C:\Users\Jordan\Desktop\League NN\DB"\models\ABR_TJMCS_DenseUniform_5_1024.h5" and the "AttributeError: 'NoneType' object has no attribute 'predict'" error comes up when I try hitting the predict button, then the program crashes.

I think it just can't find the db file. It has a " sign right after DB in the path (DB"\models\) for some reason. Not sure how to fix that. Must be the way the strings are being concatenated?

**Comment by JordanShackelford** [comment]
Seems to work now. I had quotes around my database path in config.ini and after removing that the script was able to find the directory
