### ISSUE TITLE
API expired

### ISSUE THREAD

**Issue by godfatherlmh** [vingtfranc/LoLAnalyzer#7]
Hi, I find that the stat from 7.17 is still somehow useful for picking the right champ, therefore I want to update the model to new 9.5 patch. But I can't even run the ConfigUpdater.py due to a API issue 403. 

"  File "ConfigUpdater.py", line 113, in <module>
    run()
  File "ConfigUpdater.py", line 78, in run
    PATCHES = api.getData('https://na1.api.riotgames.com/lol/static-data/v3/versions')
  File "C:\Users\lmh\Downloads\LoLAnalyzer-master (1)\LoLAnalyzer-master\InterfaceAPI.py", line 97, in getData
    raise ApiError403('API-KEY has EXPIRED. Please set the new one in config.ini (https://developer.riotgames.com/)')
InterfaceAPI.ApiError403: API-KEY has EXPIRED. Please set the new one in config.ini (https://developer.riotgames.com/)"

**Comment by VRichardJP** [comment]
Hi, 

Do you have an API key from Riot's developer portal?
Also, the API has changed quite a bit, so the links in the code have to be updated accordingly (and fields etc). If you have a valid key and get an error like this, it's very likely the interface is not available anymore

**Comment by godfatherlmh** [comment]
I use the newly updated api key from the riot api dashboard, but it keeps return 403 error code.

**Comment by godfatherlmh** [comment]
> Hi,
> 
> Do you have an API key from Riot's developer portal?
> Also, the API has changed quite a bit, so the links in the code have to be updated accordingly (and fields etc). If you have a valid key and get an error like this, it's very likely the interface is not available anymore

I just find out that the lol-static-data-v3 API has been deprecated leaving Data Dragon as the sole source of truth for static data. It is sad that I am not familiar with coding but I find that your analyzer is much more accurate than other counter picker such as "https://www.metasrc.com/5v5/counterpicker" or "http://lolmasters.net/diamond/championselect". Those so-called counter pickers would suggest playing malzahar against nocturne which is hard to understand even for a skillful malzahar main.

**Comment by godfatherlmh** [comment]
After some coding by changing "v3" to "v4" and directly fetch data from data dragon, I finally managed to produce config.ini. Thanks again.
